### ISSUE TITLE
Make the Readme.md more readable

### ISSUE THREAD

**Issue by abhinuvpitale** [abhinuvpitale/Machine-Learning-Examples#1]

**Comment by veshitala** [comment]
Hey @abhinuvpitale , I'm new in this field. I have recently completed machine learning and deep learning course on coursera By Andrew Ng.may i proceed with this

**Comment by varishtsg** [comment]
Hi @veshitala if you haven't started working on it, can I give it a shot?

**Comment by Hobbesball** [comment]
started working on it, if anyone else is interested feel free to work on it as well and we can compare changes :)

**Comment by veshitala** [comment]
> Hi @veshitala if you haven't started working on it, can I give it a shot?

yes go ahead and make it awesome
all the best

**Comment by Hobbesball** [comment]
finished my version of updated README.MD, making a pull request. You can find my changes [in this fork](https://github.com/Calvinwuyts/Machine-Learning-Examples/blob/master/README.md)

[Pull request here](https://github.com/abhinuvpitale/Machine-Learning-Examples/pull/4)

**Comment by abhinuvpitale** [comment]
Thank you for the PR @Calvinwuyts , 
@veshitala  and @senpaivg  you can add them over changes done by @Calvinwuyts .

But I am closing the issue as the repo seems a lot better now
